# Generated by Django 5.0.6 on 2024-07-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='commets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Data', models.DateField()),
                ('Massages', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
